---
user: "{{ ansible_user_id }}"
home: "{{ ansible_user_dir }}"

# role: brew
brew_taps:
  - caskroom/cask
  - caskroom/fonts
  - homebrew/python
  - homebrew/versions

brew_packages:
  - awscli
  - chruby
  - colordiff
  - coreutils
  - ctags
  - direnv
  - docker
  - docker-compose
  - docker-machine
  - doxygen
  - findutils
  - fzf
  - gawk
  - ghq
  - gibo
  - gist
  - git
  - gnu-sed
  - go
  - graphviz
  - heroku
  - hub
  - imagemagick
  - jo
  - jq
  - mysql
  - node6-lts
#  - python3
  - reattach-to-user-namespace
  - ruby-install
  - shellcheck
  - ssh-copy-id
  - terminal-notifier
  - terraform
  - the_silver_searcher
  - tidy-html5
  - tig
  - tmux
  - zplug
  - { name: zsh, install_options: without-etcdir }
#  - { name: emacs, install_options: with-cocoa }
#  - { name: cask, install_options: '' }      # must be installed after emacs
#  - { name: global, install_options: 'with-exuberant-ctags,with-pygments' }
#  - { name: matplotlib, install_options: with-python3 }
#  - { name: scipy, install_options: with-python3 }

brew_cask_packages:
  - alfred
  - atom
  - betterzipql
  - clipy
  - dropbox
  - font-noto-sans-cjk-jp
  - font-ricty-diminished
  - font-source-code-pro
  - google-chrome
  - google-japanese-ime
  - hyperswitch
  - iterm2
  - karabiner
  - keycastr
  - kindle
  - licecap
  - macs-fan-control
  - magicprefs
  - pomello
  - postman
  - qlcolorcode
  - qlimagesize
  - qlmarkdown
  - qlstephen
  - quicklook-csv
  - quicklook-json
  - rescuetime
  - sequel-pro
  - skitch
  - slack
  - spectacle
  - toggldesktop
  - vagrant
  - virtualbox
  - visual-studio-code

# role: itiut.pip-packages
#pip_packages_executable: pip3
#pip_packages_install:
#  - 'ipython[notebook]'
#  - flake8
#  - pandas

# role: repositories
repositories_root: "{{ home }}/src"
repositories_repos:
  - github.com/itiut/dotfiles

# role: dotfiles
dotfiles_dirs:
  - dir: "{{ home }}/src/github.com/itiut/dotfiles/linked"
    dotfiles:
      - .aspell.conf
      - .atom
      - .config/autostart/guake.desktop
      - .config/fontconfig/fonts.conf
      - .editorconfig
      - .emacs.d
      - .gemrc
      - .gitconfig
      - .gitignore_global
      - .jsbeautifyrc
      - .jscsrc
      - .my.cnf
      - .pryrc
      - .rspec
      - .rubocop.yml
      - .ruby-version
      - .tigrc
      - .vimrc
      - .zshenv
      - .zshrc
  - dir: "{{ home }}/Dropbox/.share"
    dotfiles:
      - .aws/config
      - .aws/credentials
      - .config/hub
      - .gist
      - .gitconfig.local
      - .ssh/config
      - .zshenv.local
