language: objective-c
os:
  - osx
before_install:
  - mkdir -p
      ~/Dropbox/.share/.ssh
  - touch
      ~/Dropbox/.share/.gitconfig.local
      ~/Dropbox/.share/.ssh/config
      ~/Dropbox/.share/.zshenv.local
install:
  - bundle install
  - brew update
  - brew install ansible
  - ansible-galaxy install -r requirements.yml
  - ansible-playbook site.yml -v
script:
  - rake spec
