---
- hosts: localhost
  user: itiut

  roles:
    - { role: cui, tags: ['cui'] }
    - { role: docker, tags: ['docker'] }
    - { role: gui, tags: ['gui'] }
    - { role: linuxbrew, tags: ['linuxbrew'] }
    - { role: mysql, tags: ['mysql'] }
    - { role: ruby, tags: ['ruby'] }

  tasks:
    - name: create group by DESKTOP_SESSION
      group_by: key={{ ansible_env.DESKTOP_SESSION }}
      tags:
        - desktop

- hosts: ubuntu

  roles:
    - { role: ubuntu, tags: ['ubuntu'] }
    - { role: vagrant, tags: ['vagrant'] }

- hosts: xubuntu
