---
- hosts: localhost
  connection: local

  vars_files:
    - vars/common.yml

  roles:
    - { role: itiut.pacman, tags: ['pacman'], when: ansible_pkg_mgr == 'pacman', sudo: true }
    - { role: repository, tags: ['repository'] }
    - { role: dotfile,    tags: ['dotfile'] }
    - { role: loginshell, tags: ['loginshell'] }
