---
- hosts: 127.0.0.1
  user: itiut

  vars:
    user: itiut
    home: /home/{{ user }}
    local_dir: "{{ home }}/local"
    src_dir: "{{ local_dir }}/src"

  roles:
    - role: cui
    - role: gui
    - role: node
    - role: ruby

  tasks:
    - name: create group
      group_by: key={{ ansible_env.DESKTOP_SESSION }}


- hosts: ubuntu

  # roles:
  #   - role: vagrant

  tasks:
    - include: tasks/ubuntu.yml
  #   - include: tasks/emacs.yml

- hosts: xubuntu
