---
- hosts: 127.0.0.1
  user: itiut

  vars:
    user: itiut
    home: /home/{{ user }}

  roles:
    - role: cui
    - role: ruby
    - role: vagrant

  tasks:
    - include: tasks/apt-get.yml
    - include: tasks/emacs.yml
