---
- hosts: localhost
  connection: local

  vars_files:
    - [ "vars/{{ ansible_os_family }}.yml", vars/os_defaults.yml ]
    - vars/common.yml

  roles:
    - { role: apt,        tags: ['apt'],        when: ansible_os_family == 'Debian' }
    - { role: brew,       tags: ['brew'] }
    - { role: repository, tags: ['repository'] }
    - { role: dotfile,    tags: ['dotfile'] }
    - { role: loginshell, tags: ['loginshell'] }

#     - { role: docker, tags: ['docker'] }
#     - { role: mysql, tags: ['mysql'] }
#     - { role: vagrant, tags: ['vagrant'] }
