---
- hosts: 127.0.0.1
  user: itiut

  vars:
    user: itiut
    home: /home/{{ user }}

  vars_files:
    - vars/vagrant.yml

  roles:
    - role: ruby

  tasks:
    - include: tasks/apt-get.yml
    - include: tasks/emacs.yml
    - include: tasks/vagrant.yml
    - include: tasks/zsh.yml
