---
- hosts: localhost
  connection: local

  vars_files:
    - vars/common.yml

  roles:
    - { role: itiut.pacman, tags: ['pacman'], when: ansible_pkg_mgr == 'pacman', sudo: true }
    - { role: osxc.packages, tags: ['osxc'], when: ansible_os_family == 'Darwin' }
    - { role: repository, tags: ['repository'] }
    - { role: dotfile,    tags: ['dotfile'] }
    - { role: loginshell, tags: ['loginshell'] }
