---
- hosts: localhost
  connection: local

  vars_files:
    - vars/main.yml

  roles:
    - { role: brew, tags: ['brew'] }
    - { role: itiut.pip-packages, tags: ['pip'] }
    - { role: repositories, tags: ['repositories'] }
    - { role: dotfiles, tags: ['dotfiles'] }
    - { role: loginshell, tags: ['loginshell'] }
