---
- hosts: 127.0.0.1
  user: itiut

  vars:
    user: itiut
    home: /home/{{ user }}
    local_dir: "{{ home }}/local"
    src_dir: "{{ local_dir }}/src"

  roles:
    - role: cui
    - role: gui
    - role: ruby
