---
- name: "emacs | add-apt-repository ppa:cassou/emacs"
  apt_repository: repo='ppa:cassou/emacs'
  sudo: yes

- name: "emacs | apt-get install emcas24"
  apt: pkg=emacs24
  sudo: yes

- name: "emacs | create local desktop entry directory"
  file: path={{ home }}/.local/share/applications state=directory

- name: "emacs | set LANG=ja_JP.UTF-8 environment"
  shell: cat /usr/share/applications/emacs24.desktop
         | sed 's/^\(Exec=\)\(\/usr\/bin\/emacs24\)/\1env LANG=ja_JP.UTF-8 \2/'
         > {{ home }}/.local/share/applications/emacs24.desktop
         creates={{ home }}/.local/share/applications/emacs24.desktop
