---
- name: Create directories in which symlinks will be located
  file:
    path="{{ home }}/{{ item.1 | dirname }}"
    state=directory
  with_subelements:
    - dotfiles_dirs
    - dotfiles
  when: item.1 is string and item.1 | search("/")

- name: Create symlinks to dotfiles
  file:
    src="{{ item.0.dir }}/{{ item.1.file | default(item.1) }}"
    dest="{{ home }}/{{ item.1.link | default(item.1) }}"
    state=link
  with_subelements:
    - dotfiles_dirs
    - dotfiles
