---
- name: "Add Homebrew's zsh to /etc/shells"
  lineinfile: dest=/etc/shells line=/usr/local/bin/zsh
  sudo: yes

- name: Check if login shell is set to zsh
  shell: dscl . -read {{ home }} UserShell | cut -d ' ' -f 2
  register: old_shell

- name: Change login shell to zsh
  shell: dscl . -change {{ home }} UserShell {{ old_shell.stdout }} /usr/local/bin/zsh
  sudo: yes
  when: old_shell.stdout != '/usr/local/bin/zsh'
