---
- name: Check if login shell is set to zsh
  shell: dscl . -read {{ home }} UserShell | cut -d ' ' -f 2
  register: old_shell
  changed_when: false

- name: Set login shell to zsh
  shell: dscl . -change {{ home }} UserShell {{ old_shell.stdout }} {{ zsh_path }}
  become: yes
  when: old_shell.stdout != "{{ zsh_path }}"
