---
- name: install packages dependent to linuxbrew
  apt: pkg={{ item }}
  sudo: yes
  with_items:
    - build-essential
    - curl
    - git
    - libbz2-dev
    - libcurl4-openssl-dev
    - libexpat1-dev
    - libncurses5-dev
    - zlib1g-dev
    - ruby
    - autoconf                  # for ruby-build
    - rake                      # for hub

- name: linuxbrew repository
  git: repo=https://github.com/Homebrew/linuxbrew.git dest={{ home }}/.linuxbrew

- name: copy linuxbrew init script
  copy: src=linuxbrew.sh dest={{ home }}/.bash_profile.linuxbrew

- name: source linuxbrew init script in .bash_profile
  lineinfile: dest={{ home }}/.bash_profile line="source $HOME/.bash_profile.linuxbrew" create=yes mode=0644

- name: install packages by linuxbrew
  homebrew: name={{ item }} path={{ home }}/.linuxbrew/bin
  with_items:
    - gist
    - heroku-toolbelt
    - hub
    - node
    - rbenv
    - ruby-build
