---
# TODO: fix
# - name: install packages dependent to linuxbrew
#   apt: pkg={{ item }}
#   sudo: yes
#   with_items:
#     - build-essential
#     - curl
#     - git
#     - libbz2-dev
#     - libcurl4-openssl-dev
#     - libexpat1-dev
#     - libncurses5-dev
#     - zlib1g-dev
#     - ruby
#     - autoconf                  # for ruby-build
#     - rake                      # for hub

- name: Install Linuxbrew
  git: repo=https://github.com/Homebrew/linuxbrew.git dest={{ home }}/.linuxbrew

- name: Update Linuxbrew
  homebrew: update_homebrew=yes path={{ home }}/.linuxbrew/bin

- name: Install packages by Linuxbrew
  homebrew: name={{ item.name }} install_options='{{ item.install_options | default() }}' path={{ home }}/.linuxbrew/bin
  with_items: linuxbrew_packages
