---
- name: Install packages dependent to Linuxbrew
  apt: name={{ item }}
  sudo: yes
  with_items:
    - build-essential
    - curl
    - git
    - m4
    - ruby
    - texinfo
    - libbz2-dev
    - libcurl4-openssl-dev
    - libexpat1-dev
    - libncurses5-dev
    - zlib1g-dev
    # TODO: fix
    # - autoconf                  # for ruby-build
    # - rake                      # for hub

- name: Install Linuxbrew
  git: repo=https://github.com/Homebrew/linuxbrew.git dest={{ home }}/.linuxbrew

- name: Update Linuxbrew
  homebrew: update_homebrew=yes path={{ home }}/.linuxbrew/bin

- name: Install packages by Linuxbrew
  homebrew: name={{ item.name }} install_options='{{ item.install_options | default() }}' path={{ home }}/.linuxbrew/bin
  with_items: linuxbrew_packages
