---
- name: Install packages dependent to Linuxbrew
  apt: name={{ item }}
  sudo: yes
  with_items:
    - build-essential
    - curl
    - git
    - m4
    - rake
    - ruby
    - texinfo
    - libbz2-dev
    - libcurl4-openssl-dev
    - libexpat1-dev
    - libncurses5-dev
    - zlib1g-dev

- name: Install Linuxbrew
  git: repo=https://github.com/Homebrew/linuxbrew.git dest={{ home }}/.linuxbrew
