---
- name: Update brew
  homebrew: update_homebrew=yes path={{ brew_path }}

# TODO: support Linuxbrew
- name: Tap repositories
  homebrew_tap: tap={{ item }}
  with_items: homebrew_taps
  when: "ansible_os_family == 'Darwin'"

- include: homebrew.yml
  when: "ansible_os_family == 'Darwin'"

- name: Install packages via brew
  homebrew: name={{ item.name }} install_options='{{ item.install_options | default() }}' path={{ brew_path }}
  with_items: brew_packages
