---
- name: Update Homebrew
  homebrew:
    update_homebrew=yes
  when: "{{ brew_update_homebrew }}"

- name: Tap repositories
  homebrew_tap:
    tap="{{ item }}"
  with_items: "{{ brew_taps }}"

- name: Install Homebrew packages
  homebrew:
    name="{{ item.name | default(item) }}"
    install_options="{{ item.install_options | default(omit) }}"
  with_items: "{{ brew_packages }}"

- name: Install Homebrew Cask packages
  homebrew_cask:
    name="{{ item }}"
  with_items: "{{ brew_cask_packages }}"
