---
- name: hub repository
  git: repo=git://github.com/github/hub.git dest={{ hub_dir }}
  register: hub_repo

- name: bundle install in {{ hub_dir }}
  shell: bash -lc "bundle install chdir={{ hub_dir }}"
  when: hub_repo.changed or ruby_installed|failed

- name: rake install hub
  shell: bash -lc "PREFIX={{ local_dir }} bundle exec rake install chdir={{ hub_dir }}"
  when: hub_repo.changed or ruby_installed|failed
